services:
  whipser:
    build:
      dockerfile: Dockerfile.vulkan
      context: .
      args:
        - BASE_IMAGE_BUILD=rocm/dev-ubuntu-22.04:6.3.2-complete
        - BASE_IMAGE_RUN=rocm/dev-ubuntu-22.04:6.3.2
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:9001 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - PORT=9001
      - MODEL=/model.bin
    ports:
      - ${PORT:-9001}:9001
    volumes:
      - $WHISPER_MODEL_PATH:/model.bin
    ipc: host
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd
      - /dev/dri
