services:
  whipser:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:9001 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - PORT=9001
      - MODEL=/model.bin
    ports:
      - ${PORT:-9001}:9001
    volumes:
      - $WHISPER_MODEL_PATH:/model.bin
